services:
  - type: web
    name: laravel-web-spp
    env: php
    region: oregon
    plan: free
    buildCommand: |
      composer install --no-dev
      php artisan key:generate --force
    startCommand: |
      php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
